#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fd'

require 'getoptlong'

if __FILE__ == $PROGRAM_NAME

  opts = GetoptLong.new(
    ['--width', '-w', GetoptLong::REQUIRED_ARGUMENT],
    ['--help', '-h', GetoptLong::NO_ARGUMENT]
  )

  # A useful number of bytes/characters per output line
  # Will be used if no number is given via '-w' option
  width = 10

  opts.each do |opt, arg|
    case opt
    when '--help'
      Fd.print_help
      exit 0
    when '--width'
      width = arg.to_i
    end
  end

  ARGV.each do |fn|
    begin
      Fd.new(width).dump(fn)
    rescue ArgumentError => err
      puts "fd doesn't work, this way:"
      puts err.message, ''
      Fd.print_help
    end
  end
end
