#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fd'

require 'getoptlong'

if __FILE__ == $PROGRAM_NAME

  opts = GetoptLong.new(
    ['--width', '-w', GetoptLong::REQUIRED_ARGUMENT],
    ['--help', '-h', GetoptLong::NO_ARGUMENT]
  )

  # A useful number of bytes/characters per output line
  # Will be used if no number is given via '-w' option
  width = 10

  opts.each do |opt, arg|
    case opt
    when '--help'
    when '--width'
      width = arg.to_i
    end
  end

  puts "Remaining args: #{ARGV.join(', ')}"

  ARGV.each do |fn|
    puts fn
    Fd.new(width).dump(fn)
  end
end
