name: Ruby Tests

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby-version: ['3.3.11', '3.4.9', '4.0.5', 'truffleruby', 'truffleruby+graalvm']
    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
